version: "3"

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "dpaste"
      MYSQL_PASSWORD: "dpaste"
      MYSQL_DATABASE: "dpaste"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    image: mysql:5.7
    volumes:
      - data_db:/var/lib/mysql

  db_migrations:
    build:
      context: .
      target: build
      args:
        BUILD_EXTRAS: dev
    command: bash -c "sleep 10; ./manage.py makemigrations && ./manage.py migrate"
    depends_on:
      - db
    image: app
    environment:
      DB_HOST: db
      DB_NAME: dpaste
      DB_PASS: dpaste
      DB_USER: dpaste
    links:
      - db

  app:
    command: bash -c "sleep 15; ./manage.py runserver 0:8000"
    depends_on:
      - db_migrations
    environment:
      DB_HOST: db
      DB_NAME: dpaste
      DB_PASS: dpaste
      DB_USER: dpaste
      PORT: 8000
    image: app
    links:
      - db
    ports:
      - "8000:8000"
    restart: always
    stdin_open: true
    tty: true


volumes:
  data_db:
