# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpaste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='level',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='tree_id',
        ),
    ]
