# Generated by Django 2.0.3 on 2018-03-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpaste', '0004_auto_20180107_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='highlighted',
        ),
    ]
