# Generated by Django 3.2.4 on 2021-07-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpaste', '0007_snippet_rtl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lexer',
            field=models.CharField(default='js', max_length=30, verbose_name='Lexer'),
        ),
    ]
