name: CI (Python, Docker Build)

on: [ push, pull_request ]

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox
  
  django:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Django tests (via Docker-Compose)
        run: make test

  build-image:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Echo tag
        id: echotag
        run: |
          echo "Building an image with the following tag:"
          echo $GITHUB_SHA
          echo "Based off the following commit:"
          echo $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image Only
        id: build
        env:
          ECR_REGISTRY: ci-run
          ECR_REPOSITORY: pastebin
          IMAGE_TAG: $GITHUB_SHA
        run: docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA .
